export const CommentsData = [
  {
    name: "Andy",
    text: "Morbi efficitur gravida massa sed maximus.",
    replies: [],
  },
  {
    name: "Joe",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    replies: [
      {
        name: "Andy",
        text: "Morbi eu risus ut metus lacinia mollis",
        replies: [
          {
            name: "Anna",
            text: "Morbi efficitur gravida massa sed maximus",
            replies: [
              {
                name: "Kevin",
                text: "Maecenas a nulla a arcu fermentum accumsan",
                replies: [
                  {
                    name: "Mark",
                    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
                    replies: [],
                  },
                ],
              },
            ],
          },
          {
            name: "Billy",
            text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
            replies: [],
          },
          {
            name: "Thomas",
            text: "Morbi eu risus ut metus lacinia mollis",
            replies: [
              {
                name: "Paul",
                text: "Proin commodo odio eget orci elementum, non aliquam est mollis",
                replies: [
                  {
                    name: "Kevin",
                    text: "Maecenas a nulla a arcu fermentum accumsan",
                    replies: [
                      {
                        name: "Gary",
                        text: "Proin commodo odio eget",
                        replies: [
                          {
                            name: "Martin",
                            text: "Morbi efficitur gravida massa sed maximus",
                            replies: [],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Martin",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    replies: [],
  },
  {
    name: "Joseph",
    text: "Morbi eu risus ut metus lacinia mollis",
    replies: [],
  },
  {
    name: "Billy",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    replies: [
      {
        name: "Kevin",
        text: "Maecenas a nulla a arcu fermentum accumsan",
        replies: [
          {
            name: "Gary",
            text: "Proin commodo odio eget",
            replies: [
              {
                name: "Martin",
                text: "Morbi efficitur gravida massa sed maximus",
                replies: [],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Justin",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    replies: [],
  },
  {
    name: "Thomas",
    text: "Morbi eu risus ut metus lacinia mollis",
    replies: [
      {
        name: "Lea",
        text: "Nam quis mauris quis massa interdum dictum non et augue",
        replies: [],
      },
    ],
  },
];

const NameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];

const Messages = [
  "I was looking for video like this",
  "Must watch for all",
  "You are a great example for others.",
  "You have great ideas.",
  "Nice one",
  "Hello",
  "It was amazing",
  "When I grow up I want to be you!",
  "I appreciate all of your opinions.",
];

export function generateRandomName() {
  return NameList[Math.floor(Math.random() * NameList.length)];
}

export function generateRandomMessage() {
  return Messages[Math.floor(Math.random() * Messages.length)];
}

export function refactorVideoCount(count) {
  let result = Math.round(count / 1000000);
  if (result > 1) {
    return `${result}M views`;
  }
  return `${Math.round(count / 1000)}K views`;
}

export function checkAndReplaceSpecialCharacters(entity) {
  if (entity.includes("&amp;")) {
    entity = entity.replaceAll("&amp;", "&");
  }
  return entity;
}
